version: "3.7"

volumes:
  mssql-data:

services:
    
        map-of-subdivisions-api:
            build:
                dockerfile: Dockerfile
            ports: 
                - 25000:80
            depends_on: 
                - database
            restart: always


        database:
            container_name: sql-server-db
            image: mcr.microsoft.com/mssql/server:2019-latest
            restart: always
            volumes:
                - mssql-data:/mssql/data
            environment:
                SA_PASSWORD: "Thesecretpassword_1"
                ACCEPT_EULA: "Y"

            ports:
                - "1433:1433"


        frontend:
            build:
                context: ../../Frontend/newapp
                dockerfile: Dockerfile
            container_name: frontend-for-map-api
            restart: always
            ports:
                - 9000:3000
                - 10000:80
                - 11000:443
         
